import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import { ProductProvider } from "@/context/productContext";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { getUser } from "./(root)/(auth)/authActions/getUser";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUser();
  return (
    <ProductProvider initialUser={user?.id || null}>
      <html lang="en">
        <body
          className={`${poppins.className} ${inter.variable} grid grid-rows-[auto_1fr_auto] antialiased`}
        >
          <Navbar />
          <main className="pt-20 flex flex-col min-h-screen">
            <div className="grow px-10! max-md:px-1! max-sm:px-0">
              {children}
            </div>
            <Footer />
          </main>
          <Toaster expand richColors />
          <SpeedInsights />
        </body>
      </html>
    </ProductProvider>
  );
}
