import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Inter } from "next/font/google";
import "./globals.css";
import { ProductProvider } from "../../context/productContext";
import Navbar from "../../components/Navbar/Navbar";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // حدد الأوزان اللي محتاجها
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProductProvider>
      <html lang="en">
        {/* ${geistMono.variable}  */}
        <body
          className={`${poppins.variable} ${inter.variable} font-poppins antialiased px-10 max-md:!px-1 max-sm:px-0`}
        >
          <Navbar />
          <div className="pt-20">{children}</div>
          <Toaster expand richColors />
        </body>
      </html>
    </ProductProvider>
  );
}
