export const firstProduct = [
  {
    id: "P1-01",
    name: "Leather Bag",
    img: "/images/productImages/bag.webp",
    description: "A stylish leather bag perfect for daily use and travel.",
    imgGallery: [],
    rate: 4.5,
    stock: 12,
    discount: 15,
    discount_type: "percentage",
    price: 1200,
    options: [{ optionTitle: "Color", values: ["Black", "Brown"] }],
    active: true,
    reviews: [
      {
        userId: "U1",
        username: "Alice",
        rating: 5,
        comment: "Great quality and very durable!",
      },
      {
        userId: "U2",
        username: "Mohamed",
        rating: 4,
        comment: "Nice design but a bit heavy.",
      },
    ],
  },
  {
    id: "P1-02",
    name: "Wireless Controller",
    img: "/images/productImages/Controller.webp",
    description: "Ergonomic wireless controller with haptic feedback.",
    imgGallery: ["/images/productImages/Controller.webp"],
    rate: 4.7,
    stock: 0,
    discount: 300,
    discount_type: "mixed",
    price: 1500,
    options: [{ optionTitle: "Color", values: ["White", "Black", "Red"] }],
    active: false,
    reviews: [
      {
        userId: "U3",
        username: "Sarah",
        rating: 5,
        comment: "Best controller I’ve ever used!",
      },
      {
        userId: "U4",
        username: "Omar",
        rating: 4,
        comment: "Very responsive, but a bit pricey.",
      },
    ],
  },
  {
    id: "P1-03",
    name: "Gaming Cooler",
    img: "/images/productImages/cooler.webp",
    description: "High-performance gaming cooler with RGB lighting.",
    imgGallery: ["/images/productImages/cooler.webp"],
    rate: 4.2,
    stock: 8,
    discount: 10,
    discount_type: "percentage",
    price: 800,
    options: [{ optionTitle: "Size", values: ["120mm", "240mm"] }],
    active: true,
    reviews: [
      {
        userId: "U5",
        username: "James",
        rating: 4,
        comment: "Keeps my PC cool even under heavy load.",
      },
    ],
  },
  {
    id: "P1-04",
    name: "Mechanical Keyboard",
    img: "/images/productImages/keyboard.webp",
    description: "RGB mechanical keyboard with customizable keys.",
    imgGallery: [],
    rate: 4.8,
    stock: 20,
    discount: 100,
    discount_type: "mixed",
    price: 600,
    options: [{ optionTitle: "Switch Type", values: ["Blue", "Red", "Brown"] }],
    active: true,
    reviews: [
      {
        userId: "U6",
        username: "Ahmed",
        rating: 5,
        comment: "Amazing typing experience and beautiful lights!",
      },
    ],
  },
  {
    id: "P1-05",
    name: "Mini Bookshelf",
    img: "/images/productImages/Library.webp",
    description: "Compact bookshelf perfect for small spaces.",
    imgGallery: [],
    rate: 4.0,
    stock: 0,
    discount: 0,
    discount_type: "",
    price: 350,
    options: [{ optionTitle: "Color", values: ["White", "Oak"] }],
    active: false,
    reviews: [
      {
        userId: "U7",
        username: "Hana",
        rating: 4,
        comment: "Good quality but a bit smaller than expected.",
      },
    ],
  },
  {
    id: "P1-06",
    name: "Smart TV 55”",
    img: "/images/productImages/TV.webp",
    description: "4K Ultra HD Smart TV with voice control.",
    imgGallery: ["/images/productImages/TV.webp"],
    rate: 4.9,
    stock: 5,
    discount: 20,
    discount_type: "percentage",
    price: 7000,
    options: [{ optionTitle: "Size", values: ["55 inch", "65 inch"] }],
    active: true,
    reviews: [
      {
        userId: "U8",
        username: "Mona",
        rating: 5,
        comment: "Picture quality is stunning!",
      },
      {
        userId: "U9",
        username: "David",
        rating: 5,
        comment: "Easy to use and excellent sound system.",
      },
    ],
  },
];
export const secondProduct = [
  {
    id: "P2-01",
    name: "Leather Bag 2",
    img: "/images/productImages/bag.webp",
    description: "A stylish leather bag perfect for daily use and travel.",
    imgGallery: [],
    rate: 4.5,
    stock: 12,
    discount: 15,
    discount_type: "percentage",
    price: 1200,
    options: [{ optionTitle: "Color", values: ["Black", "Brown"] }],
    active: true,
    reviews: [
      {
        userId: "U2-01",
        username: "Alice",
        rating: 5,
        comment: "Great quality and very durable!",
      },
      {
        userId: "U2-02",
        username: "Mohamed",
        rating: 4,
        comment: "Nice design but a bit heavy.",
      },
    ],
  },
  {
    id: "P2-02",
    name: "Wireless Controller 2",
    img: "/images/productImages/Controller.webp",
    description: "Ergonomic wireless controller with haptic feedback.",
    imgGallery: ["/images/productImages/Controller.webp"],
    rate: 4.7,
    stock: 0,
    discount: 200,
    discount_type: "mixed",
    price: 1500,
    options: [{ optionTitle: "Color", values: ["White", "Black", "Red"] }],
    active: false,
    reviews: [
      {
        userId: "U2-03",
        username: "Sarah",
        rating: 5,
        comment: "Best controller I’ve ever used!",
      },
      {
        userId: "U2-04",
        username: "Omar",
        rating: 4,
        comment: "Very responsive, but a bit pricey.",
      },
    ],
  },
  {
    id: "P2-03",
    name: "Gaming Cooler 2",
    img: "/images/productImages/cooler.webp",
    description: "High-performance gaming cooler with RGB lighting.",
    imgGallery: ["/images/productImages/cooler.webp"],
    rate: 4.2,
    stock: 8,
    discount: 10,
    discount_type: "percentage",
    price: 800,
    options: [{ optionTitle: "Size", values: ["120mm", "240mm"] }],
    active: true,
    reviews: [
      {
        userId: "U2-05",
        username: "James",
        rating: 4,
        comment: "Keeps my PC cool even under heavy load.",
      },
    ],
  },
  {
    id: "P2-04",
    name: "Mechanical Keyboard 2",
    img: "/images/productImages/keyboard.webp",
    description: "RGB mechanical keyboard with customizable keys.",
    imgGallery: [],
    rate: 4.8,
    stock: 20,
    discount: 50,
    discount_type: "mixed",
    price: 600,
    options: [{ optionTitle: "Switch Type", values: ["Blue", "Red", "Brown"] }],
    active: true,
    reviews: [
      {
        userId: "U2-06",
        username: "Ahmed",
        rating: 5,
        comment: "Amazing typing experience and beautiful lights!",
      },
    ],
  },
  {
    id: "P2-05",
    name: "Mini Bookshelf 2",
    img: "/images/productImages/Library.webp",
    description: "Compact bookshelf perfect for small spaces.",
    imgGallery: [],
    rate: 4.0,
    stock: 0,
    discount: 0,
    discount_type: "",
    price: 350,
    options: [{ optionTitle: "Color", values: ["White", "Oak"] }],
    active: false,
    reviews: [
      {
        userId: "U2-07",
        username: "Hana",
        rating: 4,
        comment: "Good quality but a bit smaller than expected.",
      },
    ],
  },
  {
    id: "P2-06",
    name: "Smart TV 55” 2",
    img: "/images/productImages/TV.webp",
    description: "4K Ultra HD Smart TV with voice control.",
    imgGallery: ["/images/productImages/TV.webp"],
    rate: 4.9,
    stock: 5,
    discount: 20,
    discount_type: "percentage",
    price: 7000,
    options: [{ optionTitle: "Size", values: ["55 inch", "65 inch"] }],
    active: true,
    reviews: [
      {
        userId: "U2-08",
        username: "Mona",
        rating: 5,
        comment: "Picture quality is stunning!",
      },
      {
        userId: "U2-09",
        username: "David",
        rating: 5,
        comment: "Easy to use and excellent sound system.",
      },
    ],
  },
];
export const thirdProduct = [
  {
    id: "P3-01",
    name: "Leather Bag 3",
    img: "/images/productImages/bag.webp",
    description: "A stylish leather bag perfect for daily use and travel.",
    imgGallery: [],
    rate: 4.5,
    stock: 12,
    discount: 15,
    discount_type: "percentage",
    price: 1200,
    options: [{ optionTitle: "Color", values: ["Black", "Brown"] }],
    active: true,
    reviews: [
      {
        userId: "U3-01",
        username: "Alice",
        rating: 5,
        comment: "Great quality and very durable!",
      },
      {
        userId: "U3-02",
        username: "Mohamed",
        rating: 4,
        comment: "Nice design but a bit heavy.",
      },
    ],
  },
  {
    id: "P3-02",
    name: "Wireless Controller 3",
    img: "/images/productImages/Controller.webp",
    description: "Ergonomic wireless controller with haptic feedback.",
    imgGallery: ["/images/productImages/Controller.webp"],
    rate: 4.7,
    stock: 0,
    discount: 0,
    discount_type: "",
    price: 1500,
    options: [{ optionTitle: "Color", values: ["White", "Black", "Red"] }],
    active: false,
    reviews: [
      {
        userId: "U3-03",
        username: "Sarah",
        rating: 5,
        comment: "Best controller I’ve ever used!",
      },
      {
        userId: "U3-04",
        username: "Omar",
        rating: 4,
        comment: "Very responsive, but a bit pricey.",
      },
    ],
  },
  {
    id: "P3-03",
    name: "Gaming Cooler 3",
    img: "/images/productImages/cooler.webp",
    description: "High-performance gaming cooler with RGB lighting.",
    imgGallery: ["/images/productImages/cooler.webp"],
    rate: 4.2,
    stock: 8,
    discount: 10,
    discount_type: "percentage",
    price: 800,
    options: [{ optionTitle: "Size", values: ["120mm", "240mm"] }],
    active: true,
    reviews: [
      {
        userId: "U3-05",
        username: "James",
        rating: 4,
        comment: "Keeps my PC cool even under heavy load.",
      },
    ],
  },
  {
    id: "P3-04",
    name: "Mechanical Keyboard 3",
    img: "/images/productImages/keyboard.webp",
    description: "RGB mechanical keyboard with customizable keys.",
    imgGallery: [],
    rate: 4.8,
    stock: 20,
    discount: 0,
    discount_type: "",
    price: 600,
    options: [{ optionTitle: "Switch Type", values: ["Blue", "Red", "Brown"] }],
    active: true,
    reviews: [
      {
        userId: "U3-06",
        username: "Ahmed",
        rating: 5,
        comment: "Amazing typing experience and beautiful lights!",
      },
    ],
  },
  {
    id: "P3-05",
    name: "Mini Bookshelf 3",
    img: "/images/productImages/Library.webp",
    description: "Compact bookshelf perfect for small spaces.",
    imgGallery: [],
    rate: 4.0,
    stock: 0,
    discount: 0,
    discount_type: "",
    price: 350,
    options: [{ optionTitle: "Color", values: ["White", "Oak"] }],
    active: false,
    reviews: [
      {
        userId: "U3-07",
        username: "Hana",
        rating: 4,
        comment: "Good quality but a bit smaller than expected.",
      },
    ],
  },
  {
    id: "P3-06",
    name: "Smart TV 55” 3",
    img: "/images/productImages/TV.webp",
    description: "4K Ultra HD Smart TV with voice control.",
    imgGallery: ["/images/productImages/TV.webp"],
    rate: 4.9,
    stock: 5,
    discount: 20,
    discount_type: "percentage",
    price: 7000,
    options: [{ optionTitle: "Size", values: ["55 inch", "65 inch"] }],
    active: true,
    reviews: [
      {
        userId: "U3-08",
        username: "Mona",
        rating: 5,
        comment: "Picture quality is stunning!",
      },
      {
        userId: "U3-09",
        username: "David",
        rating: 5,
        comment: "Easy to use and excellent sound system.",
      },
    ],
  },
];
export const components = [
  {
    title: "Best Selling Products",
    products: firstProduct,
    id: "1",
    category: "fashion",
  },
  {
    title: "Flash Sales",
    products: secondProduct,
    id: "2",
    category: "gaming",
  },
  {
    title: "Explore Our Products",
    products: thirdProduct,
    id: "3",
    category: "entertainment",
  },
];
